# Generated by Django 4.0.1 on 2022-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_email', models.EmailField(max_length=100)),
                ('available_balance', models.IntegerField()),
                ('transfered_amount', models.IntegerField()),
                ('destination_accountnumber', models.IntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
