# Generated by Django 4.0.1 on 2022-03-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_transactionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='destination_accountnumber',
            new_name='source_accountnumber',
        ),
    ]
